### ISSUE TITLE
Signal billing_resume is not registered for this plugin.

### ISSUE THREAD

**Issue by chrisdugne** [godot-sdk-integrations/godot-google-play-billing#31]
Hello,
I compiled version `1.1.1` using latest [master](https://github.com/godotengine/godot-google-play-billing/tree/adfcef8522975918a51967504375082d34881645) 

My app crash as soon as it's launched;
I found this cause:

```sh
Caused by: java.lang.IllegalArgumentException: Signal billing_resume is not registered for this plugin.
	at org.godotengine.godot.plugin.GodotPlugin.emitSignal(GodotPlugin.java:327)
	at org.godotengine.godot.plugin.googleplaybilling.GodotGooglePlayBilling.onMainResume(GodotGooglePlayBilling.java:283)
	at org.godotengine.godot.Godot.onResume(Godot.java:876)
```

so I'm currently commenting the line which emits the signal: https://github.com/godotengine/godot-google-play-billing/blob/adfcef8522/godot-google-play-billing/src/main/java/org/godotengine/godot/plugin/googleplaybilling/GodotGooglePlayBilling.java#L283

I can now proceed with the billing flow, so it's a workaround for me now, but there should be a fix I think;

**Comment by allkhor** [comment]
PR for this : https://github.com/godotengine/godot-google-play-billing/pull/30
